apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      containers:
      - name: vote-service
        image: ggcr.io/temp-j7ryensp-wsky/voteservice
        ports:
        - containerPort: 80
        env:
        - name: CLOUD_SQL_CONNECTION_NAME
          value: "temp-j7ryensp-wsky:us-central1:vote-app-instance"
        - name: DB_USER
          value: "vote-app-instance"
        - name: DB_PASS
          value: "ASHWINI"
        - name: DB_NAME
          value: "vote-app"
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
